version: "3.9"  # Use a more recent version

services:
  client:
    build: 
      context: ./frontend
    ports:
      - "4200:4200"
      - "9229:9229" 
    volumes:
      - ./frontend/src:/usr/src/app/src 

  server:
    build: 
      context: ./backend
      target: base  # If you have multiple build stages in your Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URL=${MONGODB_URL} 
    volumes:
      - ./backend/src:/usr/src/app/src
      - ./backend/nodemon.json:/usr/src/app/nodemon.json
    depends_on:
      - database
    command: npm run dev

  database:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_data: